### ISSUE TITLE
[BUG] Unable to parse large CEL expression

### ISSUE THREAD

**Issue by ZeLonewolf** [onthegomap/planetiler#1025]
I am unable to enter a CL expression of greater than 100K in size.  I encountered this in processing machine-generated YAML in the following form:

```
layers:
  - id: boundary
    features:
      - source: osm
        geometry: polygon
        min_zoom: 5
        include_when:
          - ${feature.id in [4569,7444,11240,11282,11950,11957,11958,11978,11988,16132,17529,18000,18311,18316,18318,18326,18328,18349,18350,18351,18352...
```

The stack trace is here:

```
        at com.onthegomap.planetiler.custommap.expression.ConfigExpressionScript.parse(ConfigExpressionScript.java:114)
        at com.onthegomap.planetiler.custommap.expression.BooleanExpressionScript.script(BooleanExpressionScript.java:27)
        at com.onthegomap.planetiler.custommap.BooleanExpressionParser.parse(BooleanExpressionParser.java:86)
        at com.onthegomap.planetiler.custommap.BooleanExpressionParser.parse(BooleanExpressionParser.java:77)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toArray(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.toList(Unknown Source)
        at com.onthegomap.planetiler.custommap.BooleanExpressionParser.parse(BooleanExpressionParser.java:90)
        at com.onthegomap.planetiler.custommap.BooleanExpressionParser.parse(BooleanExpressionParser.java:77)
        at com.onthegomap.planetiler.custommap.BooleanExpressionParser.parse(BooleanExpressionParser.java:54)
        at com.onthegomap.planetiler.custommap.ConfiguredFeature.<init>(ConfiguredFeature.java:64)
        at com.onthegomap.planetiler.custommap.ConfiguredProfile.<init>(ConfiguredProfile.java:54)
        at com.onthegomap.planetiler.custommap.ConfiguredMapMain.main(ConfiguredMapMain.java:51)
        at com.onthegomap.planetiler.Main.main(Main.java:102)
Caused by: org.projectnessie.cel.tools.ScriptCreateException: parse failed: ERROR: <input>:-1:0: expression code point size exceeds limit: size: 1529805, limit 100000
        at org.projectnessie.cel.tools.ScriptHost$ScriptBuilder.build(ScriptHost.java:129)
        at com.onthegomap.planetiler.custommap.expression.ConfigExpressionScript.parse(ConfigExpressionScript.java:110)
        ... 19 more
```

**Comment by msbarry** [comment]
This isn't a straightforward change to make since the limit is buried deep inside CEL and not configurable easily. I did open an issue against the CEL library https://github.com/projectnessie/cel-java/issues/615 to make this more easily configurable, but I really don't think people should be using giant CEL expressions since they will be very slow.

For your particular use-case I added the ability to use expressions on the left-hand side of a match statement in #1063. Feel free to re-open if you have another use-case not covered by this.
