### ISSUE TITLE
Docker command not working, No matches for 'Monaco'

### ISSUE THREAD

**Issue by d3netxer** [onthegomap/planetiler#302]
last lines of Docker command output:

```
0:00:00 INF - Building BasemapProfile profile into data/output.mbtiles in these phases:
0:00:00 INF -   download: Download sources [lake_centerlines, water_polygons, natural_earth, osm]
0:00:00 INF -   lake_centerlines: Process features in data/sources/lake_centerline.shp.zip
0:00:00 INF -   water_polygons: Process features in data/sources/water-polygons-split-3857.zip
0:00:00 INF -   natural_earth: Process features in data/sources/natural_earth_vector.sqlite.zip
0:00:00 INF -   osm_pass1: Pre-process OpenStreetMap input (store node locations then relation members)
0:00:00 INF -   osm_pass2: Process OpenStreetMap nodes, ways, then relations
0:00:00 INF -   sort: Sort rendered features by tile ID
0:00:00 INF -   mbtiles: Encode each tile and write to data/output.mbtiles
0:00:00 INF [download] -
0:00:00 INF [download] - Starting...
Exception in thread "main" java.lang.IllegalArgumentException: No matches for 'Monaco'
        at com.onthegomap.planetiler.util.Geofabrik.searchIndexForDownloadUrl(Geofabrik.java:101)
        at com.onthegomap.planetiler.util.Geofabrik.getDownloadUrl(Geofabrik.java:47)
        at com.onthegomap.planetiler.util.Downloader.add(Downloader.java:149)
        at com.onthegomap.planetiler.Planetiler.download(Planetiler.java:680)
        at com.onthegomap.planetiler.Planetiler.run(Planetiler.java:504)
        at com.onthegomap.planetiler.basemap.BasemapMain.run(BasemapMain.java:51)
        at com.onthegomap.planetiler.basemap.BasemapMain.main(BasemapMain.java:14)
        at com.onthegomap.planetiler.Main.main(Main.java:57)
```

**Comment by msbarry** [comment]
Looks like it was a temporary issue on geofabrik's side, should be resolved now!
