### ISSUE TITLE
There was a problem during execution

### ISSUE THREAD

**Issue by dongliangde** [onthegomap/planetiler#531]
An error occurred：
```
Worker osm_pass1_process-1 died
java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.onthegomap.planetiler.util.ThreadLocalTransliterator.getInstance(ThreadLocalTransliterator.java:25)
        at com.onthegomap.planetiler.util.Translations.lambda$static$0(Translations.java:22)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at com.onthegomap.planetiler.util.Translations.transliterate(Translations.java:146)
        at com.onthegomap.planetiler.util.LanguageUtils.transliteratedName(LanguageUtils.java:51)
        at org.openmaptiles.util.OmtLanguageUtils.getNames(OmtLanguageUtils.java:92)
        at org.openmaptiles.layers.Waterway.preprocessOsmRelation(Waterway.java:152)
        at com.onthegomap.planetiler.ForwardingProfile.preprocessOsmRelation(ForwardingProfile.java:98)
        at com.onthegomap.planetiler.reader.osm.OsmReader.processPass1Blocks(OsmReader.java:259)
        at com.onthegomap.planetiler.worker.WorkerPipeline$Builder.lambda$sinkTo$2(WorkerPipeline.java:275)
        at com.onthegomap.planetiler.worker.Worker.lambda$new$0(Worker.java:41)
        at com.onthegomap.planetiler.worker.Worker.lambda$new$1(Worker.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.MissingResourceException: Could not find the bundle com/ibm/icu/impl/data/icudt72b/translit/root
        at com.ibm.icu.impl.ResourceBundleWrapper.getBundleInstance(ResourceBundleWrapper.java:134)
        at com.ibm.icu.util.UResourceBundle.instantiateBundle(UResourceBundle.java:389)
        at com.ibm.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:149)
        at com.ibm.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:110)
        at com.ibm.icu.text.Transliterator.<clinit>(Transliterator.java:2172)
        ... 22 more
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: com.onthegomap.planetiler.util.Exceptions$FatalPlanetilerException: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at com.onthegomap.planetiler.util.Exceptions.throwFatalException(Exceptions.java:29)
        at com.onthegomap.planetiler.stats.ProgressLoggers.await(ProgressLoggers.java:367)
        at com.onthegomap.planetiler.stats.ProgressLoggers.awaitAndLog(ProgressLoggers.java:352)
        at com.onthegomap.planetiler.reader.osm.OsmReader.pass1(OsmReader.java:221)
        at com.onthegomap.planetiler.Planetiler.lambda$addOsmSource$0(Planetiler.java:199)
        at com.onthegomap.planetiler.Planetiler.lambda$ifSourceUsed$9(Planetiler.java:841)
        at com.onthegomap.planetiler.Planetiler.run(Planetiler.java:720)
        at org.openmaptiles.OpenmaptilesApplication.run(OpenmaptilesApplication.java:55)
        at org.openmaptiles.OpenmaptilesApplication.main(OpenmaptilesApplication.java:15)
        ... 8 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ExceptionInInitializerError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
        at com.onthegomap.planetiler.stats.ProgressLoggers.await(ProgressLoggers.java:361)
        ... 15 more
Caused by: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.onthegomap.planetiler.util.ThreadLocalTransliterator.getInstance(ThreadLocalTransliterator.java:25)
        at com.onthegomap.planetiler.util.Translations.lambda$static$0(Translations.java:22)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at com.onthegomap.planetiler.util.Translations.transliterate(Translations.java:146)
        at com.onthegomap.planetiler.util.LanguageUtils.transliteratedName(LanguageUtils.java:51)
        at org.openmaptiles.util.OmtLanguageUtils.getNames(OmtLanguageUtils.java:92)
        at org.openmaptiles.layers.Waterway.preprocessOsmRelation(Waterway.java:152)
        at com.onthegomap.planetiler.ForwardingProfile.preprocessOsmRelation(ForwardingProfile.java:98)
        at com.onthegomap.planetiler.reader.osm.OsmReader.processPass1Blocks(OsmReader.java:259)
        at com.onthegomap.planetiler.worker.WorkerPipeline$Builder.lambda$sinkTo$2(WorkerPipeline.java:275)
        at com.onthegomap.planetiler.worker.Worker.lambda$new$0(Worker.java:41)
        at com.onthegomap.planetiler.worker.Worker.lambda$new$1(Worker.java:68)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.util.MissingResourceException: Could not find the bundle com/ibm/icu/impl/data/icudt72b/translit/root
        at com.ibm.icu.impl.ResourceBundleWrapper.getBundleInstance(ResourceBundleWrapper.java:134)
        at com.ibm.icu.util.UResourceBundle.instantiateBundle(UResourceBundle.java:389)
        at com.ibm.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:149)
        at com.ibm.icu.util.UResourceBundle.getBundleInstance(UResourceBundle.java:110)
        at com.ibm.icu.text.Transliterator.<clinit>(Transliterator.java:2172)
        ... 22 more

```
The icu was installed according to the error that occurred, but the icu still cannot be found during the execution process !
https://github.com/unicode-org/icu source code to install ICU library
command execution result：
`icu-config --version`
`69.1`

**Comment by msbarry** [comment]
You shouldn't need ICU installed on your system, the resource should be included in the built jars. I see you're using spring boot, that might be loading resources differently?

**Comment by dongliangde** [comment]
> You shouldn't need ICU installed on your system, the resource should be included in the built jars. I see you're using spring boot, that might be loading resources differently?

Yes, I saw the ICU jar in pom.xml, but the same problem still occurs after packaging. Now I have taken the update code and changed the ThreadLocalTransliterator getInstance method under the com.onthegomap.planetiler.util package to
```
   public TransliteratorInstance getInstance(String id) {
        Transliterator t = Transliterator.getInstance(id);
        return t::transliterate;
    }
```
It can be executed when running the project, but it is not sure what problems will occur when modifying this code

**Comment by msbarry** [comment]
Ohh right I remember now... the ICU transliterator shares one global instance and access to it is synchronized which limits parallelism. The thread local transliterator creates a custom classloader so each thread can have its own copy that doesn't need to be synchronized.  I can see how that would cause issues with other classloaders...

It should run fine with those changes, just a little slower.  It would be nice if planetiler automatically fell back to that if there was any issue with the custom classloader. If you wanted to submit a patch could you detect that detected that extra exception in `ThreadLocalTransliterator` and just fell back to the normal behavior on failure?

Something like:

```java
    } catch (ClassNotFoundException | InvocationTargetException | NoSuchMethodException | IllegalAccessException | ExceptionInInitializerError e) {
      Transliterator t = Transliterator.getInstance(id);
      return t::transliterate;
    }
```
