### ISSUE TITLE
[BUG] NPEs while generating planet

### ISSUE THREAD

**Issue by msbarry** [onthegomap/planetiler#69]
While generating the planet, there were a few NPEs:

```
0:33:28 ERR [osm_pass2:process] - Error processing OSM way 121137742
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.Map.get(Object)" is null
	at com.onthegomap.planetiler.basemap.layers.Transportation.getMinzoom(Transportation.java:424)
	at com.onthegomap.planetiler.basemap.layers.Transportation.process(Transportation.java:362)
	at com.onthegomap.planetiler.basemap.BasemapProfile.lambda$new$6(BasemapProfile.java:134)
	at com.onthegomap.planetiler.ForwardingProfile.processFeature(ForwardingProfile.java:116)
	at com.onthegomap.planetiler.reader.osm.OsmReader.lambda$pass2$2(OsmReader.java:279)
	at com.onthegomap.planetiler.worker.WorkerPipeline$Builder.lambda$addWorker$0(WorkerPipeline.java:246)
	at com.onthegomap.planetiler.worker.Worker.lambda$new$0(Worker.java:49)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

```
0:38:40 ERR [osm_pass2:process] - Error processing OSM way 283144232
java.lang.NullPointerException
```

```
0:51:06 ERR [osm_pass2:process] - Error processing OSM way 712454442
java.lang.NullPointerException
```

**Comment by tyrauber** [comment]
Hi @msbarry, Should this resolved on main?  I pulled yesterday, and I am seeing a lot of NPE errors while generating a planet file.

```
ERR [osm_pass2:process] - Error processing OSM Node 21596054
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.onthegomap.planetiler.util.Parse.parseIntOrNull(String)" is null
	at com.protomaps.basemap.layers.Places.processFeature(Places.java:35)
	at com.onthegomap.planetiler.ForwardingProfile.processFeature(ForwardingProfile.java:116)
	at com.onthegomap.planetiler.reader.osm.OsmReader.render(OsmReader.java:467)
	at com.onthegomap.planetiler.reader.osm.OsmReader.lambda$pass2$6(OsmReader.java:359)
	at com.onthegomap.planetiler.worker.WorkerPipeline$Builder.lambda$addWorker$0(WorkerPipeline.java:252)
	at com.onthegomap.planetiler.worker.Worker.lambda$new$0(Worker.java:41)
	at com.onthegomap.planetiler.worker.Worker.lambda$new$1(Worker.java:68)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	0:23:55 ERR [osm_pass2:process] - Error processing OSM Node 3471197002
java.lang.NullPointerException
0:23:55 ERR [osm_pass2:process] - Error processing OSM Node 3472734763
java.lang.NullPointerException
0:23:55 ERR [osm_pass2:process] - Error processing OSM Node 3474949831
java.lang.NullPointerException
0:23:56 ERR [osm_pass2:process] - Error processing OSM Node 3489134123
java.lang.NullPointerException
0:23:56 ERR [osm_pass2:process] - Error processing OSM Node 3494710763
java.lang.NullPointerException
0:23:57 ERR [osm_pass2:process] - Error processing OSM Node 3495696649
java.lang.NullPointerException
0:23:57 ERR [osm_pass2:process] - Error processing OSM Node 3501032732
java.lang.NullPointerException
0:23:57 ERR [osm_pass2:process] - Error processing OSM Node 3506478907
java.lang.NullPointerException
0:23:57 ERR [osm_pass2:process] - Error processing OSM Node 3506478910
java.lang.NullPointerException
```
Should I be concerned? Or let it do it's thing?

Thanks for your work here. Most appreciated.

**Comment by msbarry** [comment]
I think that's an issue in the protomaps base layer code:

https://github.com/protomaps/basemaps/blob/e069e40e59fab46ce7ceeadca19dabcb7bafa133/tiles/src/main/java/com/protomaps/basemap/layers/Places.java#L35-L40

`parseIntOrNull` returns null if the input is not a valid integer, but then `int population = Parse.parseIntOrNull(...)` tries to unbox it which fails. I think that should check if the result is not null then unbox from `Integer` to `int`

cc/ @bdon

**Comment by tyrauber** [comment]
My apologies, @msbarry, I should have saw that. Definitely the issue.  Running a patch now. I'll continue to tail the logs, but so far so good.  @bdon I'll submit a PR shortly.  Thanks again, Michael.
