### ISSUE TITLE
[BUG] Downloader error getting size of GitHub zipball

### ISSUE THREAD

**Issue by wipfli** [onthegomap/planetiler#928]
**Describe the bug**

I would like to use the Downloader to get a zipball from GitHub but the execution fails. 

**To Reproduce**

1. Create a `power.java` file with this content:
```java
import java.nio.file.Path;

import com.onthegomap.planetiler.FeatureCollector;
import com.onthegomap.planetiler.Planetiler;
import com.onthegomap.planetiler.util.Downloader;
import com.onthegomap.planetiler.Profile;
import com.onthegomap.planetiler.config.Arguments;
import com.onthegomap.planetiler.reader.SourceFeature;

/**
 * Generates vector tiles with power lines from OpenStreetMap (see
 * https://wiki.openstreetmap.org/wiki/Tag:power%3Dline)
 * 
 * To run:
 * - java -cp planetiler.jar Power.java
 * - open power.pmtiles in https://pmtiles.io
 */
public class Power implements Profile {

  public static void main(String[] args) {
    var arguments = Arguments.fromArgs(args).withDefault("download", true);
    String area = arguments.getString("area", "geofabrik area to download", "rhode-island");
    var planetiler = Planetiler.create(arguments);

    Path dataDir = Path.of("data");
    Path sourcesDir = dataDir.resolve("sources");

    Downloader.create(planetiler.config())
      .add("pgf-encoding", "https://api.github.com/repos/wipfli/pgf-encoding/zipball/main", sourcesDir.resolve("pgf-encoding.zip")).run();


    planetiler.addOsmSource("osm", Path.of("data", area + ".osm.pbf"), "geofabrik:" + area)
        .overwriteOutput(Path.of("power.pmtiles"))
        .setProfile(new Power())
        .run();
  }

  @Override
  public void processFeature(SourceFeature sourceFeature, FeatureCollector features) {
    if (sourceFeature.canBeLine() && sourceFeature.hasTag("power", "line")) {
      features.line("power")
          .inheritAttrFromSource("voltage");
    }
  }

  @Override
  public String attribution() {
    return OSM_ATTRIBUTION;
  }

  @Override
  public boolean isOverlay() {
    return true;
  }
}
```
2. Download the latest jar `wget https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar`
3. Run with just-in-time java 22 `java -cp planetiler.jar Power.java`
4. See error:
```
Exception in thread "main" java.lang.IllegalStateException: Error getting size of https://api.github.com/repos/wipfli/pgf-encoding/zipball/main
        at com.onthegomap.planetiler.util.Downloader.run(Downloader.java:174)
        at Power.main(Power.java:29)
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
        at com.onthegomap.planetiler.util.Downloader.run(Downloader.java:168)
        at Power.main(Power.java:29)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.execute(SourceLauncher.java:264)
        at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.run(SourceLauncher.java:153)
        at jdk.compiler/com.sun.tools.javac.launcher.SourceLauncher.main(SourceLauncher.java:78)
```

**Expected behavior**
Should download the zip file.

**Environment (please complete the following information):**

- OS: Ubuntu
```
$ java --version
openjdk 22.0.1 2024-04-16
OpenJDK Runtime Environment Temurin-22.0.1+8 (build 22.0.1+8)
OpenJDK 64-Bit Server VM Temurin-22.0.1+8 (build 22.0.1+8, mixed mode, sharing)
```

**Comment by wipfli** [comment]
Maybe the problem is that the GitHub api want some HTTP headers like for example `User-Agent`, see https://docs.github.com/en/rest/using-the-rest-api/getting-started-with-the-rest-api?apiVersion=2022-11-28#headers.

**Comment by wipfli** [comment]
Works perfectly. Thanks @msbarry!
